# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchSystem', '0002_author_feed_liveradiodictionary_radioprogram_subjectuserprogram'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='liveradioplaylist',
            table='live_radio_play_list',
        ),
    ]
