# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchSystem', '0003_auto_20160329_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUser',
            fields=[
                ('user_ptr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='searchSystem.AuthUser')),
                ('login_type', models.IntegerField()),
                ('weibo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('birth', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=1, null=True)),
                ('tastes', models.CharField(blank=True, max_length=1, null=True)),
                ('subjects', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'log_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramTopn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programid', models.CharField(db_column='programID', max_length=50)),
                ('programtype', models.CharField(db_column='programType', max_length=45)),
                ('count', models.BigIntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'program_topn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RbcProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('subjects', models.CharField(blank=True, max_length=45, null=True)),
                ('block_name', models.CharField(blank=True, max_length=255, null=True)),
                ('radio_id', models.IntegerField(blank=True, null=True)),
                ('play_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rbc_play_link', models.CharField(blank=True, max_length=255, null=True)),
                ('insert_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'rbc_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField(blank=True, null=True)),
                ('program_duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tmp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgramCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('program_id', models.IntegerField(blank=True, null=True)),
                ('dir_type', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_program_collect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgramExplicitBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('program_id', models.IntegerField()),
                ('star', models.IntegerField(blank=True, null=True)),
                ('share', models.IntegerField(blank=True, null=True)),
                ('collect', models.IntegerField(blank=True, null=True)),
                ('insert_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_program_explicit_behavior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgramScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('program_id', models.IntegerField()),
                ('play_count', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_program_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRecommendPlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('play_time', models.CharField(blank=True, max_length=45, null=True)),
                ('program_id', models.IntegerField()),
                ('dir_type', models.IntegerField(blank=True, null=True)),
                ('is_played', models.IntegerField(blank=True, null=True)),
                ('generate_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_recommend_play_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('login_type', models.IntegerField()),
                ('weibo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('birth', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=45, null=True)),
                ('tastes', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStationCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('radio_id', models.IntegerField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_station_collect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStationExplicitBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('radio_id', models.IntegerField()),
                ('collect', models.IntegerField(blank=True, null=True)),
                ('insert_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_station_explicit_behavior',
                'managed': False,
            },
        ),
    ]
